apiVersion: v1
kind: Service
metadata:
  name: webserver-nodeport-service
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
